## provide the name of the namespace
namespace:
  name: sandbox

## define the image to execute with the Deployment
image:
  repository: schildner/techtrends
  tag: latest
  pullPolicy: IfNotPresent

## set the number of replicas for an application
replicaCount: 1

service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

resources:
  requests:
    memory: 64Mi
    cpu: 250m
  limits:
    memory: 128Mi
    cpu: 500m

containerPort: 3111
livenessProbe:
  path: /healthz
readinessProbe:
  path: /healthz
  initialDelaySeconds: 60
